'use client';

import { PokerTableClient } from '../[tableId]/PokerTableClient';
import type { GameState } from '@/lib/poker/types';

const MOCK_STATE_9: GameState = {
  tableId: 'preview-9',
  tableName: '하이롤러 테이블',
  smallBlind: 100,
  bigBlind: 200,
  maxSeats: 9,
  handId: 'hand-009',
  handNumber: 12,
  street: 'turn',
  communityCards: ['Ah', 'Ks', '7d', 'Tc'] as any,
  pot: 4800,
  sidePots: [],
  currentSeat: 0,
  currentBet: 600,
  minRaise: 400,
  dealerSeat: 8,
  seats: [
    {
      seatNumber: 0,
      userId: 'hero-id',
      nickname: 'Hero',
      chipStack: 8500,
      holeCards: ['As', 'Kd'] as any,
      betInRound: 200,
      totalBetInHand: 800,
      isFolded: false,
      isAllIn: false,
      isSittingOut: false,
      isActive: true,
    },
    {
      seatNumber: 1,
      userId: 'p1',
      nickname: 'FishKing',
      chipStack: 3200,
      holeCards: null,
      betInRound: 0,
      totalBetInHand: 200,
      isFolded: true,
      isAllIn: false,
      isSittingOut: false,
      isActive: true,
    },
    {
      seatNumber: 2,
      userId: 'p2',
      nickname: 'SharkBoy',
      chipStack: 12400,
      holeCards: null,
      betInRound: 600,
      totalBetInHand: 1200,
      isFolded: false,
      isAllIn: false,
      isSittingOut: false,
      isActive: true,
    },
    {
      seatNumber: 3,
      userId: 'p3',
      nickname: 'PokerKing',
      chipStack: 6100,
      holeCards: null,
      betInRound: 0,
      totalBetInHand: 200,
      isFolded: true,
      isAllIn: false,
      isSittingOut: false,
      isActive: true,
    },
    {
      seatNumber: 4,
      userId: 'p4',
      nickname: 'AceHunter',
      chipStack: 5500,
      holeCards: null,
      betInRound: 600,
      totalBetInHand: 1000,
      isFolded: false,
      isAllIn: false,
      isSittingOut: false,
      isActive: true,
    },
    {
      seatNumber: 5,
      userId: 'p5',
      nickname: 'TiltMachine',
      chipStack: 4100,
      holeCards: null,
      betInRound: 600,
      totalBetInHand: 1000,
      isFolded: false,
      isAllIn: false,
      isSittingOut: false,
      isActive: true,
    },
    {
      seatNumber: 6,
      userId: 'p6',
      nickname: 'BluffMaster',
      chipStack: 0,
      holeCards: null,
      betInRound: 0,
      totalBetInHand: 4200,
      isFolded: false,
      isAllIn: true,
      isSittingOut: false,
      isActive: true,
    },
    {
      seatNumber: 7,
      userId: 'p7',
      nickname: 'NitQueen',
      chipStack: 9800,
      holeCards: null,
      betInRound: 0,
      totalBetInHand: 400,
      isFolded: true,
      isAllIn: false,
      isSittingOut: false,
      isActive: true,
    },
    {
      seatNumber: 8,
      userId: 'p8',
      nickname: 'LuckyAce',
      chipStack: 7200,
      holeCards: null,
      betInRound: 600,
      totalBetInHand: 1400,
      isFolded: false,
      isAllIn: false,
      isSittingOut: false,
      isActive: true,
    },
  ],
  lastAction: { seat: 8, action: 'raise', amount: 600 },
  actionClosedBySeat: null,
  turnTimeLeft: 18,
  status: 'playing',
};

export default function PokerPreviewPage() {
  return (
    <PokerTableClient
      tableId="preview-9"
      initialState={MOCK_STATE_9}
      userId="hero-id"
      nickname="Hero"
    />
  );
}
